### ISSUE TITLE
Provide plugin.type definition for fluent-bit config

### ISSUE THREAD

**Issue by ricegi** [newrelic/newrelic-logs-salesforce-eventlogfile#10]
## Summary

Provide a means to help NR customer identify their salesforce logs 

## Desired Behavior

could we add plugin.type=salesforce as identifier for this integration? This will help customer to identify their salesforce logs

## Possible Solution

could we add plugin.type=salesforce as identifier for this integration? This will help customer to identify their salesforce logs

**Comment by asllop** [comment]
@ricegi we already added some attributes to identify data generated by this integration:

- `intrumentation.name` = `salesforce-eventlogfile`
- `intrumentation.version` = integration version, current is `1.0.0`
- `intrumentation.provider` = `newrelic-labs`
- `collector.name` = `newrelic-logs-salesforce-eventlogfile`

Is it enough?
