### ISSUE TITLE
Salesforce Event logs are not reflected in NewRelic SFDC Overview dashboards.

### ISSUE THREAD

**Issue by ashokdhupati** [newrelic/newrelic-logs-salesforce-eventlogfile#11]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Salesforce Event logs are not reflected in NewRelic SFDC Overview dashboards.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## integration_name: com.newrelic.labs.sfdc.eventlogfiles
run_as_service: False
cron_interval_minutes: 1440
service_schedule: { "hour":  "*", "minute": "30" }
instances:
  - name: sfdc-logs
    arguments:
      token_url: "https://login.salesforce.com/services/oauth2/token"
      auth: {
        "grant_type": "password",
        "client_id": "xxxxx",
        "client_secret": "xxxxx",
        "username": "xxxx",
        "password": "xxxx"
      }
      cache_enabled: false
      redis: {
        "host": "",
        "port": "",
        "db_number": 0,
        "password": ""
      }
      date_field: "LogDate"
      generation_interval: "Hourly"
      time_lag_minutes: 60
    labels:
      environment: production
newrelic:
  data_format: "events"
  api_endpoint: "US"
  account_id: ""
  license_key: ""

  
When I run this command event logs are posted but not seeing anything on SFDC overview dashboards.
![image](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/2a520305-ad51-4dc7-941d-ab3b35c939a8)
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 2000 events from log file URI/0ATRg000000PNDQOA4
posted 665 events from log file URI/0ATRg000000PNDQOA4
posted 316 events from log file VisualforceRequest/0ATRg000000PNDROA4
PS C:\Users\AshokDhupati\GIT\newrelic-logs-salesforce-eventlogfile> python src/__main__.py   

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by asllop** [comment]
@ashokdhupati we released [v1.0.0](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/releases/tag/1.0.0) last week. Could you test it and check if the issue is still there?

**Comment by ashokdhupati** [comment]
@asllop I have tried new version , but now I am facing new issue. Can you guys help me on this ?
![Screenshot 2024-02-16 124338](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/ac773296-48e6-4145-b4c9-baceb0409526)

**Comment by asllop** [comment]
Hi @ashokdhupati ! I can see that you copied the `config_sample.yml` file. Please keep in mind that this file is just an example and contains many options that might not work for you, for example, that reference to `other_queries.yml`, you probably don't have this file. Please read the [documentation](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/blob/main/README.md) carefully in order to write a proper config.yml file.

**Comment by ashokdhupati** [comment]
Hi @asllop, that was a config file alignment issue that I have fixed, but we wanted to track flow and apex exception logs.

**Comment by ashokdhupati** [comment]
Hi @asllop, Will you be able to help with tracking flow and apex exception logs in the new relic?

**Comment by asllop** [comment]
Hi @ashokdhupati, unfortunately this is not the place, the issue tracker is exclusively for bugs and improvements requests in the project code, not for usage/configuration related questions. For this kind of issues, please ask your New Relic account manager or New Relic help forums.

**Comment by ashokdhupati** [comment]
Hi @asllop , I am facing new issue today when I ran the project. Can you please take a look at it.

![Screenshot 2024-02-28 105147](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/938a162c-4708-4bd9-b36b-3b263e266e6c)
