### ISSUE TITLE
I have tried new version , but now I am facing new issue. Can you guys help me on this ?

### ISSUE THREAD

**Issue by ashokdhupati** [newrelic/newrelic-logs-salesforce-eventlogfile#17]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
![Screenshot 2024-02-16 124338](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/72efa3b5-d6d8-444e-bbba-513056ad2999)
While running the command python src/__main__.py , I am seeing this issue.

**Comment by ashokdhupati** [comment]
I have tried the same queries in Salesforce to retrieve the data and those are working fine but in VS code I am seeing time time stamp issue 
![Screenshot 2024-02-17 110404](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/assets/150742130/af054295-ffbe-4527-91c9-eb63f7bc2953)

**Comment by asllop** [comment]
Hi @ashokdhupati , sorry but I don't see the relation between the first and second screenshots, could you clarify? Regarding the first screenshot, isn't it the same you already posted [here](https://github.com/newrelic/newrelic-logs-salesforce-eventlogfile/issues/11#issuecomment-1949101048)?
