### ISSUE TITLE
The integration does not throw an error, but does not send data to New Relic

### ISSUE THREAD

**Issue by mmattos-newrelic** [newrelic/newrelic-logs-salesforce-eventlogfile#9]
## Description
I'm helping a customer set up the integration, but despite not generating any error logs, the data is not sent to New Relic.
Only the configuration file (config.yml) has been updated with data from the customer's Sales Force instance and with data from the New Relic account. No other modifications were made to the rest of the source code.
Could this be a bug, or is there something else that needs to be modified/configured?

## Steps to Reproduce

1. Code has been downloaded to the customer's local machine
2. Configuration file has been modified with customer data only.
3. Integration was performed as instructed in README.md

## Expected Behavior

SF log information sent to New Relic and visible through the standard Dashboard available in New Relic I/O

## Relevant Logs / Console output

Key: axxxxxxxxxxxxxxxxxxxNRAL
Output: sent 50 log messages from log file Logout/0AT8L000003tiIDWAY
RPM of the test account: 4004742
<there is no error>

## Your Environment

SO: Windows 11 Home Single Language - 22H2
Python: 3.11.14

**Comment by miransar** [comment]
Solution has been provided to customer. As discussed with @mmattos-newrelic, closing this issue.

**Comment by mmattos-newrelic** [comment]
Hey, @asllop . What specific action do I need to take? Do you want me to remove the historic of changes? Thanks!

**Comment by asllop** [comment]
Hi @mmattos-newrelic, just revoke that key, and create a new one if you need. The key has been compromised already, removing any historic (if it's even possible) doesn't change that.

**Comment by mmattos-newrelic** [comment]
Now I got it. Thanks!

Miguel Mattos
Senior Solution Consultant
+55.11.9.4203-4744
***@***.*** ***@***.***>


￼

**Comment by asllop** [comment]
Thank you! I'll mark the security issue as resolved.
